services:
  update-poggit-search:
    build: .
    environment:
      TYPESENSE_API_KEY: insecure
    links:
      - typesense:typesense
    restart: on-failure

  typesense:
    image: typesense/typesense:26.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: insecure
    volumes:
      - typesense:/data
    restart: on-failure

volumes:
  typesense:
    driver: local